backend:
  name: git-gateway
  branch: main
media_folder: '/assets/media'
public_folder: '/assets/media'
collections:
  - name: 'intro'
    label: 'Intro'
    folder: '_data/bmg/intro/test'
    create: true
    slug: '---'
    fields:
      - { label: 'title', name: 'title', widget: 'string' }
